name: Release Storybook to GitHubPages

on:
  push:
    branches:
      - main

env:
  cache-version: v1

jobs:
  release:
    name: Project Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8.2.0

      - name: Install Node Dependencies
        run: pnpm install
        working-directory: ./frontend

      - name: Build package
        run: pnpm run build

      - name: Build storybook
        run: pnpm run build-storybook -o ./dist/storybook

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
